---
  # where to run the ci/cd pipeline
  pool:
    vmImage: ubuntu-22.04
  
  # when to run
  trigger:
    - main
  
  # what has to be done
  steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        Dockerfile: "./Dockerfile"
        tags: "shaikkhajaibrahim/saleor:AZDEV"
        containerRegistry: DockerHub